eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        register-with-eureka: false
        fetch-registry: false
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/bensonlim/springcloud/
          searchPaths: helloworldConfig
  application:
    name: config-server